# Generated by Django 4.1 on 2024-09-17 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_name', models.CharField(max_length=50, null=True)),
                ('attribute_id', models.CharField(max_length=50, null=True)),
                ('name', models.CharField(max_length=100)),
                ('digital_code', models.CharField(max_length=20)),
                ('is_required', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CaseForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_name', models.CharField(max_length=50, null=True)),
                ('attribute_id', models.CharField(max_length=50, null=True)),
                ('name', models.CharField(max_length=100)),
                ('digital_code', models.CharField(max_length=20)),
                ('is_required', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Colour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_name', models.CharField(max_length=50, null=True)),
                ('attribute_id', models.CharField(max_length=50, null=True)),
                ('name', models.CharField(max_length=100)),
                ('digital_code', models.CharField(max_length=20)),
                ('is_required', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='EuroAsianCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_name', models.CharField(max_length=50, null=True)),
                ('attribute_id', models.CharField(max_length=50, null=True)),
                ('name', models.CharField(max_length=100)),
                ('digital_code', models.CharField(max_length=20)),
                ('is_required', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='GadgetModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_name', models.CharField(max_length=50, null=True)),
                ('attribute_id', models.CharField(max_length=50, null=True)),
                ('name', models.CharField(max_length=100)),
                ('digital_code', models.CharField(max_length=20)),
                ('is_required', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MicroSDSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_name', models.CharField(max_length=50, null=True)),
                ('attribute_id', models.CharField(max_length=50, null=True)),
                ('name', models.CharField(max_length=100)),
                ('digital_code', models.CharField(max_length=20)),
                ('is_required', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Processor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_name', models.CharField(max_length=50, null=True)),
                ('attribute_id', models.CharField(max_length=50, null=True)),
                ('name', models.CharField(max_length=100)),
                ('digital_code', models.CharField(max_length=20)),
                ('is_required', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessorCoreQnty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_name', models.CharField(max_length=50, null=True)),
                ('attribute_id', models.CharField(max_length=50, null=True)),
                ('name', models.CharField(max_length=100)),
                ('digital_code', models.CharField(max_length=20)),
                ('is_required', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProtectionGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_name', models.CharField(max_length=50, null=True)),
                ('attribute_id', models.CharField(max_length=50, null=True)),
                ('name', models.CharField(max_length=100)),
                ('digital_code', models.CharField(max_length=20)),
                ('is_required', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='QntyOfBasicCamera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_name', models.CharField(max_length=50, null=True)),
                ('attribute_id', models.CharField(max_length=50, null=True)),
                ('name', models.CharField(max_length=100)),
                ('digital_code', models.CharField(max_length=20)),
                ('is_required', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScreenResolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_name', models.CharField(max_length=50, null=True)),
                ('attribute_id', models.CharField(max_length=50, null=True)),
                ('name', models.CharField(max_length=100)),
                ('digital_code', models.CharField(max_length=20)),
                ('is_required', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SimCardQnty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_name', models.CharField(max_length=50, null=True)),
                ('attribute_id', models.CharField(max_length=50, null=True)),
                ('name', models.CharField(max_length=100)),
                ('digital_code', models.CharField(max_length=20)),
                ('is_required', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SmartphoneModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_name', models.CharField(max_length=50, null=True)),
                ('attribute_id', models.CharField(max_length=50, null=True)),
                ('name', models.CharField(max_length=100)),
                ('digital_code', models.CharField(max_length=20)),
                ('is_required', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_name', models.CharField(max_length=50, null=True)),
                ('attribute_id', models.CharField(max_length=50, null=True)),
                ('name', models.CharField(max_length=100)),
                ('digital_code', models.CharField(max_length=20)),
                ('is_required', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='VideoQuality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_name', models.CharField(max_length=50, null=True)),
                ('attribute_id', models.CharField(max_length=50, null=True)),
                ('name', models.CharField(max_length=100)),
                ('digital_code', models.CharField(max_length=20)),
                ('is_required', models.BooleanField(default=True)),
            ],
        ),
    ]
