# Generated by Django 4.1 on 2024-09-17 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference_smartphones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='euroasiancode',
            name='name',
            field=models.CharField(max_length=300),
        ),
    ]
