# Generated by Django 4.1 on 2024-09-17 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference_smartphones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='category_dependent',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='euroasiancode',
            name='attribute_name',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='euroasiancode',
            name='digital_code',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='euroasiancode',
            name='name',
            field=models.TextField(),
        ),
    ]
