# Generated by Django 4.1 on 2024-12-16 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference_smartphones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processor',
            name='attribute_id',
            field=models.CharField(default='10313', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='processor',
            name='attribute_name',
            field=models.CharField(default='Процессор', max_length=50, null=True),
        ),
    ]
