# Generated by Django 4.1 on 2024-09-17 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference_smartphones', '0002_brand_category_dependent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='caseform',
            name='category_dependent',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='colour',
            name='category_dependent',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='euroasiancode',
            name='category_dependent',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='gadgetmodel',
            name='category_dependent',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='microsdslot',
            name='category_dependent',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='processor',
            name='category_dependent',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='processorcoreqnty',
            name='category_dependent',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='protectiongrade',
            name='category_dependent',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='qntyofbasiccamera',
            name='category_dependent',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='screenresolution',
            name='category_dependent',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='simcardqnty',
            name='category_dependent',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='smartphonemodel',
            name='category_dependent',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='type',
            name='category_dependent',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='videoquality',
            name='category_dependent',
            field=models.BooleanField(default=True),
        ),
    ]
