# Generated by Django 4.1 on 2024-09-17 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference_smartphones', '0002_alter_euroasiancode_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='euroasiancode',
            name='digital_code',
            field=models.CharField(max_length=300),
        ),
    ]
