# Generated by Django 4.1 on 2024-09-19 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference_smartphones', '0004_alter_brand_is_required_alter_caseform_is_required_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='digital_code',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='name',
        ),
        migrations.RemoveField(
            model_name='caseform',
            name='digital_code',
        ),
        migrations.RemoveField(
            model_name='caseform',
            name='name',
        ),
        migrations.RemoveField(
            model_name='colour',
            name='digital_code',
        ),
        migrations.RemoveField(
            model_name='colour',
            name='name',
        ),
        migrations.RemoveField(
            model_name='euroasiancode',
            name='digital_code',
        ),
        migrations.RemoveField(
            model_name='euroasiancode',
            name='name',
        ),
        migrations.RemoveField(
            model_name='gadgetmodel',
            name='digital_code',
        ),
        migrations.RemoveField(
            model_name='gadgetmodel',
            name='name',
        ),
        migrations.RemoveField(
            model_name='microsdslot',
            name='digital_code',
        ),
        migrations.RemoveField(
            model_name='microsdslot',
            name='name',
        ),
        migrations.RemoveField(
            model_name='processor',
            name='digital_code',
        ),
        migrations.RemoveField(
            model_name='processor',
            name='name',
        ),
        migrations.RemoveField(
            model_name='processorcoreqnty',
            name='digital_code',
        ),
        migrations.RemoveField(
            model_name='processorcoreqnty',
            name='name',
        ),
        migrations.RemoveField(
            model_name='protectiongrade',
            name='digital_code',
        ),
        migrations.RemoveField(
            model_name='protectiongrade',
            name='name',
        ),
        migrations.RemoveField(
            model_name='qntyofbasiccamera',
            name='digital_code',
        ),
        migrations.RemoveField(
            model_name='qntyofbasiccamera',
            name='name',
        ),
        migrations.RemoveField(
            model_name='screenresolution',
            name='digital_code',
        ),
        migrations.RemoveField(
            model_name='screenresolution',
            name='name',
        ),
        migrations.RemoveField(
            model_name='simcardqnty',
            name='digital_code',
        ),
        migrations.RemoveField(
            model_name='simcardqnty',
            name='name',
        ),
        migrations.RemoveField(
            model_name='smartphonemodel',
            name='digital_code',
        ),
        migrations.RemoveField(
            model_name='smartphonemodel',
            name='name',
        ),
        migrations.RemoveField(
            model_name='type',
            name='digital_code',
        ),
        migrations.RemoveField(
            model_name='type',
            name='name',
        ),
        migrations.RemoveField(
            model_name='videoquality',
            name='digital_code',
        ),
        migrations.RemoveField(
            model_name='videoquality',
            name='name',
        ),
        migrations.AddField(
            model_name='brand',
            name='dictionary_value_id',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='brand',
            name='value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='caseform',
            name='dictionary_value_id',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='caseform',
            name='value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='colour',
            name='dictionary_value_id',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='colour',
            name='value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='euroasiancode',
            name='dictionary_value_id',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='euroasiancode',
            name='value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='gadgetmodel',
            name='dictionary_value_id',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='gadgetmodel',
            name='value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='microsdslot',
            name='dictionary_value_id',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='microsdslot',
            name='value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='processor',
            name='dictionary_value_id',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='processor',
            name='value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='processorcoreqnty',
            name='dictionary_value_id',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='processorcoreqnty',
            name='value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='protectiongrade',
            name='dictionary_value_id',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='protectiongrade',
            name='value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='qntyofbasiccamera',
            name='dictionary_value_id',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='qntyofbasiccamera',
            name='value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='screenresolution',
            name='dictionary_value_id',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='screenresolution',
            name='value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='simcardqnty',
            name='dictionary_value_id',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='simcardqnty',
            name='value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='smartphonemodel',
            name='dictionary_value_id',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='smartphonemodel',
            name='value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='type',
            name='dictionary_value_id',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='type',
            name='value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='videoquality',
            name='dictionary_value_id',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='videoquality',
            name='value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='euroasiancode',
            name='attribute_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
