# Generated by Django 4.1 on 2024-09-17 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference_smartphones', '0004_brand_category_dependent_caseform_category_dependent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='euroasiancode',
            name='digital_code',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='euroasiancode',
            name='name',
            field=models.CharField(max_length=300),
        ),
    ]
