# Generated by Django 4.1 on 2024-09-21 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference_smartphones', '0005_remove_brand_digital_code_remove_brand_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='is_collection',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='caseform',
            name='is_collection',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='colour',
            name='is_collection',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='euroasiancode',
            name='is_collection',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gadgetmodel',
            name='is_collection',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='microsdslot',
            name='is_collection',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='processor',
            name='is_collection',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='processorcoreqnty',
            name='is_collection',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='protectiongrade',
            name='is_collection',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='qntyofbasiccamera',
            name='is_collection',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='screenresolution',
            name='is_collection',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='simcardqnty',
            name='is_collection',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='smartphonemodel',
            name='is_collection',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='type',
            name='is_collection',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='videoquality',
            name='is_collection',
            field=models.BooleanField(default=False),
        ),
    ]
