# Generated by Django 4.1 on 2024-09-17 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference_smartphones', '0005_alter_euroasiancode_digital_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='category_dependent',
        ),
        migrations.RemoveField(
            model_name='caseform',
            name='category_dependent',
        ),
        migrations.RemoveField(
            model_name='colour',
            name='category_dependent',
        ),
        migrations.RemoveField(
            model_name='euroasiancode',
            name='category_dependent',
        ),
        migrations.RemoveField(
            model_name='gadgetmodel',
            name='category_dependent',
        ),
        migrations.RemoveField(
            model_name='microsdslot',
            name='category_dependent',
        ),
        migrations.RemoveField(
            model_name='processor',
            name='category_dependent',
        ),
        migrations.RemoveField(
            model_name='processorcoreqnty',
            name='category_dependent',
        ),
        migrations.RemoveField(
            model_name='protectiongrade',
            name='category_dependent',
        ),
        migrations.RemoveField(
            model_name='qntyofbasiccamera',
            name='category_dependent',
        ),
        migrations.RemoveField(
            model_name='screenresolution',
            name='category_dependent',
        ),
        migrations.RemoveField(
            model_name='simcardqnty',
            name='category_dependent',
        ),
        migrations.RemoveField(
            model_name='smartphonemodel',
            name='category_dependent',
        ),
        migrations.RemoveField(
            model_name='type',
            name='category_dependent',
        ),
        migrations.RemoveField(
            model_name='videoquality',
            name='category_dependent',
        ),
    ]
