# Generated by Django 4.1 on 2024-09-17 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference_smartphones', '0006_remove_brand_category_dependent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='euroasiancode',
            name='attribute_name',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='euroasiancode',
            name='name',
            field=models.TextField(),
        ),
    ]
