# Generated by Django 4.1 on 2024-09-24 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0041_alter_smartphone_part_number_alter_smartphone_type'),
        ('app_reference_smartphones', '0007_rename_brand_brandsmartphone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Type',
            new_name='TypeSmartphone',
        ),
    ]
