# Generated by Django 4.1 on 2024-12-20 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_notebook_reference', '0005_notebookprocessorcoreqnty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyboardcolour',
            name='attribute_id',
            field=models.CharField(default='4463', max_length=50, null=True),
        ),
    ]
