# Generated by Django 4.1 on 2024-12-22 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0030_rename_windwos_version_notebook_windows_version'),
        ('app_notebook_reference', '0006_alter_keyboardcolour_attribute_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NotebookInterfacesConnectors',
            new_name='NotebookInterfacesConnector',
        ),
    ]
