# Generated by Django 4.1 on 2024-09-17 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference_smartphones', '0004_alter_brand_is_required_alter_caseform_is_required_and_more'),
        ('app_products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartphone',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_reference_smartphones.type'),
        ),
    ]
