# Generated by Django 4.1 on 2024-10-21 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0002_monitor_monitor_installation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitor',
            name='monitor_installation',
        ),
    ]
