# Generated by Django 4.1 on 2024-09-17 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference_shared', '0002_androidversion_category_dependent_and_more'),
        ('app_products', '0003_rename_stabilization_smartphone_stabilization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smartphone',
            name='sensor',
        ),
        migrations.AddField(
            model_name='smartphone',
            name='sensor',
            field=models.ManyToManyField(blank=True, to='app_reference_shared.sensor'),
        ),
    ]
