# Generated by Django 4.1 on 2024-10-30 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference_shared', '0003_alter_ozoncategory_activated'),
        ('app_products', '0005_remove_monitor_monitor_installation'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='monitor_installation',
            field=models.ManyToManyField(blank=True, to='app_reference_shared.monitorinstallation'),
        ),
    ]
