# Generated by Django 4.1 on 2024-09-17 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0006_alter_smartphone_part_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartphone',
            name='part_number',
            field=models.CharField(max_length=160, null=True),
        ),
    ]
