# Generated by Django 4.1 on 2024-11-02 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0006_monitor_monitor_installation'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='video_url',
            field=models.URLField(blank=True),
        ),
    ]
