# Generated by Django 4.1 on 2024-09-17 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0007_alter_smartphone_part_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smartphone',
            name='part_number',
        ),
    ]
