# Generated by Django 4.1 on 2024-11-16 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference_shared', '0005_alter_name_value'),
        ('app_products', '0008_alter_monitor_lighting_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitor',
            name='lighting_type',
            field=models.ManyToManyField(blank=True, to='app_reference_shared.lightningtype'),
        ),
    ]
