# Generated by Django 4.1 on 2024-09-17 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0008_remove_smartphone_part_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartphone',
            name='part_number',
            field=models.CharField(default='dgdfgdf', max_length=160),
        ),
    ]
