# Generated by Django 4.1 on 2024-12-14 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference_smartphones', '0001_initial'),
        ('app_products', '0009_alter_monitor_lighting_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartphone',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_smartphones.brandsmartphone'),
        ),
    ]
