# Generated by Django 4.1 on 2024-12-14 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference_smartphones', '0001_initial'),
        ('app_products', '0010_smartphone_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartphone',
            name='type_smartphone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_reference_smartphones.typesmartphone'),
        ),
    ]
