# Generated by Django 4.1 on 2024-12-14 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference_shared', '0008_alter_standadjustment_value'),
        ('app_products', '0011_smartphone_type_smartphone'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartphone',
            name='model_name_smartphone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_shared.modelname'),
        ),
    ]
