# Generated by Django 4.1 on 2024-09-17 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference_shared', '0013_marketingcolour_processorfrequency_sellercode'),
        ('app_products', '0012_alter_smartphone_size_alter_smartphone_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smartphone',
            name='standby_period',
        ),
        migrations.AddField(
            model_name='smartphone',
            name='stand_by_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_shared.standbyperiod'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='basic_camera_resolution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_shared.basiccamerresolution'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='battery_capacity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_shared.batterycapacity'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='front_camera_resolution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_shared.frontcamerresolution'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='life_span',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_shared.lifespan'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='marketing_colour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_shared.marketingcolour'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='processor_frequency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_shared.processorfrequency'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='product_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_shared.productset'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='record_max_speed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_shared.recordmaxspeed'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='screen_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_shared.screensize'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='seller_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_shared.sellercode'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='work_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_shared.workperiod'),
        ),
    ]
