# Generated by Django 4.1 on 2024-09-17 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0013_remove_smartphone_standby_period_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smartphone',
            old_name='stand_by_period',
            new_name='standby_period',
        ),
    ]
