# Generated by Django 4.1 on 2024-09-17 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0014_rename_stand_by_period_smartphone_standby_period'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smartphone',
            name='EAN',
        ),
    ]
