# Generated by Django 4.1 on 2024-12-19 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_notebook_reference', '0004_rename_ramextraslots_ramextraslot'),
        ('app_products', '0015_notebook_chipset_notebook_hdd_qnty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebook',
            name='ram_extra_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_notebook_reference.ramextraslot'),
        ),
    ]
