# Generated by Django 4.1 on 2024-09-19 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference_shared', '0013_marketingcolour_processorfrequency_sellercode'),
        ('app_products', '0015_remove_smartphone_ean'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smartphone',
            name='sensor',
        ),
        migrations.AddField(
            model_name='smartphone',
            name='sensor',
            field=models.ManyToManyField(blank=True, to='app_reference_shared.sensor'),
        ),
    ]
