# Generated by Django 4.1 on 2024-12-19 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_notebook_reference', '0004_rename_ramextraslots_ramextraslot'),
        ('app_reference_shared', '0014_delete_portqntyhdmi'),
        ('app_products', '0016_notebook_ram_extra_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebook',
            name='builtin_device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_shared.builtindevice'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='case_coating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_shared.casecoating'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='case_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_notebook_reference.notebookcasematerial'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='dvd_drive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_shared.dvdrive'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='interface_connector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_notebook_reference.notebookinterfacesconnectors'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='keyboard_colour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_notebook_reference.keyboardcolour'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='lan_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_shared.lancard'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='lightning_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_shared.lightningtype'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='manual_input_device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_shared.manualinputdevice'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='manual_input_device_feature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_shared.manualinputdevicefeature'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='port_hdmi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_shared.hdmiports'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='port_qnty_thunderbolt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_shared.portqntythunderbolt'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='screen_coating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_shared.screencoating'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='sound_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_shared.soundconfig'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='ssd_qnty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_notebook_reference.ssdqnty'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='video_card_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_shared.videocardtype'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='video_ram',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_notebook_reference.videoram'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='web_cam_resolution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_shared.webcamresolution'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='wifi_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_shared.wifitype'),
        ),
    ]
