# Generated by Django 4.1 on 2024-09-19 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference_shared', '0013_marketingcolour_processorfrequency_sellercode'),
        ('app_products', '0016_remove_smartphone_sensor_smartphone_sensor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smartphone',
            name='country_of_manufacture',
        ),
        migrations.AddField(
            model_name='smartphone',
            name='country_of_manufacture',
            field=models.ManyToManyField(blank=True, to='app_reference_shared.countryofmanufacture'),
        ),
    ]
