# Generated by Django 4.1 on 2024-12-19 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0017_notebook_builtin_device_notebook_case_coating_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notebook',
        ),
    ]
