# Generated by Django 4.1 on 2024-09-19 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference_shared', '0013_marketingcolour_processorfrequency_sellercode'),
        ('app_products', '0017_remove_smartphone_country_of_manufacture_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smartphone',
            name='card_type',
        ),
        migrations.AddField(
            model_name='smartphone',
            name='card_type',
            field=models.ManyToManyField(blank=True, to='app_reference_shared.cardtype'),
        ),
    ]
