# Generated by Django 4.1 on 2024-09-19 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference_shared', '0013_marketingcolour_processorfrequency_sellercode'),
        ('app_products', '0018_remove_smartphone_card_type_smartphone_card_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smartphone',
            name='navigation',
        ),
        migrations.RemoveField(
            model_name='smartphone',
            name='sim_type',
        ),
        migrations.AddField(
            model_name='smartphone',
            name='navigation',
            field=models.ManyToManyField(blank=True, to='app_reference_shared.navigationtype'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='sim_type',
            field=models.ManyToManyField(blank=True, to='app_reference_shared.simtype'),
        ),
    ]
