# Generated by Django 4.1 on 2024-12-19 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_notebook_reference', '0004_rename_ramextraslots_ramextraslot'),
        ('app_reference_shared', '0015_rename_hdmiports_hdmiport_delete_portqntydisplayport'),
        ('app_products', '0018_delete_notebook'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('battery_capacity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_shared.batterycapacity')),
                ('bluetooth', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_reference_shared.bluetoothtype')),
                ('brand_notebook', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_notebook_reference.brandnotebook')),
                ('builtin_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_shared.builtindevice')),
                ('case_coating', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_shared.casecoating')),
                ('case_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_notebook_reference.notebookcasematerial')),
                ('category_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_shared.ozoncategory')),
                ('chipset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_shared.chipset')),
                ('country_of_manufacture', models.ManyToManyField(blank=True, to='app_reference_shared.countryofmanufacture')),
                ('dvd_drive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_shared.dvdrive')),
                ('hdd_qnty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_notebook_reference.hddqnty')),
                ('interface_connector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_notebook_reference.notebookinterfacesconnectors')),
                ('keyboard_colour', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_notebook_reference.keyboardcolour')),
                ('lan_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_shared.lancard')),
                ('lightning_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_shared.lightningtype')),
                ('manual_input_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_shared.manualinputdevice')),
                ('manual_input_device_feature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_shared.manualinputdevicefeature')),
                ('notebook_form_factor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_shared.notebookformfactor')),
                ('notebook_max_ram', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_notebook_reference.notebookmaxram')),
                ('notebook_processor_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_reference_shared.processormodelnotebook')),
                ('notebook_ram', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_notebook_reference.ramnotebook')),
                ('notebook_ram_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_notebook_reference.notebookramtype')),
                ('port_hdmi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_shared.hdmiport')),
                ('port_qnty_USB', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_reference_shared.portqntyusb')),
                ('port_qnty_thunderbolt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_shared.portqntythunderbolt')),
                ('port_usb3_gen1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_shared.portqntyusb3gen1')),
                ('port_usb3_gen2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_shared.portqntyusb3gen2')),
                ('power_off_work_time', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_reference_shared.poweroffworktime')),
                ('product_set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_shared.productset')),
                ('ram_extra_slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_notebook_reference.ramextraslot')),
                ('ram_form_factor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_shared.ramformfactor')),
                ('screen_coating', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_shared.screencoating')),
                ('sound_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_shared.soundconfig')),
                ('ssd_qnty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_notebook_reference.ssdqnty')),
                ('video_card_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_shared.videocardtype')),
                ('video_ram', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_notebook_reference.videoram')),
                ('warranty_period', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_shared.warrantyperiod')),
                ('web_cam_resolution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_shared.webcamresolution')),
                ('wifi_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_shared.wifitype')),
            ],
            options={
                'verbose_name': 'notebook',
                'verbose_name_plural': 'notebooks',
            },
        ),
    ]
