# Generated by Django 4.1 on 2024-12-19 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0019_notebook'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebook',
            name='image_1',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='notebook',
            name='image_2',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='notebook',
            name='image_3',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='notebook',
            name='image_4',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='notebook',
            name='image_5',
            field=models.URLField(blank=True),
        ),
    ]
