# Generated by Django 4.1 on 2024-09-19 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference_shared', '0013_marketingcolour_processorfrequency_sellercode'),
        ('app_products', '0019_remove_smartphone_navigation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smartphone',
            name='wifi',
        ),
        migrations.AddField(
            model_name='smartphone',
            name='wifi',
            field=models.ManyToManyField(blank=True, to='app_reference_shared.wifitype'),
        ),
    ]
