# Generated by Django 4.1 on 2024-12-19 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference_shared', '0016_displayport'),
        ('app_products', '0020_notebook_image_1_notebook_image_2_notebook_image_3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebook',
            name='display_port',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_shared.displayport'),
        ),
    ]
