# Generated by Django 4.1 on 2024-09-19 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference_shared', '0013_marketingcolour_processorfrequency_sellercode'),
        ('app_reference_smartphones', '0004_alter_brand_is_required_alter_caseform_is_required_and_more'),
        ('app_products', '0020_remove_smartphone_wifi_smartphone_wifi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smartphone',
            name='camera_function',
        ),
        migrations.RemoveField(
            model_name='smartphone',
            name='colour',
        ),
        migrations.RemoveField(
            model_name='smartphone',
            name='hazard_grade',
        ),
        migrations.AddField(
            model_name='smartphone',
            name='camera_function',
            field=models.ManyToManyField(blank=True, to='app_reference_shared.camerafunction'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='colour',
            field=models.ManyToManyField(blank=True, to='app_reference_smartphones.colour'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='hazard_grade',
            field=models.ManyToManyField(blank=True, to='app_reference_shared.hazardgrade'),
        ),
    ]
