# Generated by Django 4.1 on 2024-09-19 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference_shared', '0013_marketingcolour_processorfrequency_sellercode'),
        ('app_products', '0021_remove_smartphone_camera_function_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smartphone',
            name='case_material',
        ),
        migrations.RemoveField(
            model_name='smartphone',
            name='wireless_interface',
        ),
        migrations.AddField(
            model_name='smartphone',
            name='case_material',
            field=models.ManyToManyField(blank=True, to='app_reference_shared.casematerial'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='wireless_interface',
            field=models.ManyToManyField(blank=True, to='app_reference_shared.wirelessinterface'),
        ),
    ]
