# Generated by Django 4.1 on 2024-12-19 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference_shared', '0016_displayport'),
        ('app_notebook_reference', '0004_rename_ramextraslots_ramextraslot'),
        ('app_products', '0021_notebook_display_port'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebook',
            name='battery_element_qnty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_notebook_reference.batteryelementqnty'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='battery_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_shared.batterytype'),
        ),
    ]
