# Generated by Django 4.1 on 2024-12-19 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_notebook_reference', '0004_rename_ramextraslots_ramextraslot'),
        ('app_reference_shared', '0017_alter_maxscreenfrequency_attribute_name'),
        ('app_products', '0022_notebook_battery_element_qnty_notebook_battery_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebook',
            name='max_screen_frequency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_shared.maxscreenfrequency'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='nb_screen_resolution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_notebook_reference.notebookscreenresolution'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='power_supply_voltage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_shared.powersupplyvoltage'),
        ),
    ]
