# Generated by Django 4.1 on 2024-09-19 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference_shared', '0013_marketingcolour_processorfrequency_sellercode'),
        ('app_products', '0022_remove_smartphone_case_material_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smartphone',
            name='comms_standard',
        ),
        migrations.AddField(
            model_name='smartphone',
            name='comms_standard',
            field=models.ManyToManyField(null=True, to='app_reference_shared.communicationstandard'),
        ),
    ]
