# Generated by Django 4.1 on 2024-09-19 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference_shared', '0013_marketingcolour_processorfrequency_sellercode'),
        ('app_products', '0023_remove_smartphone_comms_standard_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smartphone',
            name='charging_function',
        ),
        migrations.RemoveField(
            model_name='smartphone',
            name='special_feature',
        ),
        migrations.RemoveField(
            model_name='smartphone',
            name='stabilization',
        ),
        migrations.AddField(
            model_name='smartphone',
            name='charging_function',
            field=models.ManyToManyField(blank=True, to='app_reference_shared.chargingfunction'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='special_feature',
            field=models.ManyToManyField(blank=True, to='app_reference_shared.specialfeature'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='stabilization',
            field=models.ManyToManyField(blank=True, to='app_reference_shared.stabilization'),
        ),
    ]
