# Generated by Django 4.1 on 2024-12-19 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference_shared', '0018_rename_totalsddvolume_totalssdvolume'),
        ('app_notebook_reference', '0004_rename_ramextraslots_ramextraslot'),
        ('app_products', '0025_notebook_total_ssd_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebook',
            name='configuration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_shared.configuration'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='hazard_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_shared.hazardgrade'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='hdd_form_factor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_notebook_reference.hddformfactor'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='port_TypeC',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_shared.portqntytypec'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='screen_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_shared.screensize'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='ssd_form_factor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_notebook_reference.ssdformfactor'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='storage_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_notebook_reference.storagetype'),
        ),
    ]
