# Generated by Django 4.1 on 2024-12-19 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_notebook_reference', '0005_notebookprocessorcoreqnty'),
        ('app_reference_shared', '0018_rename_totalsddvolume_totalssdvolume'),
        ('app_products', '0026_notebook_configuration_notebook_hazard_grade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebook',
            name='marketing_colour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_shared.marketingcolour'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='nb_colour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_notebook_reference.notebookcolour'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='nb_processor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_shared.notebookprocessor'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='nb_processor_brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_shared.notebookprocessorbrand'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='nb_processor_core_qnty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_notebook_reference.notebookprocessorcoreqnty'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='nb_video_processor_brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_shared.notebookvideoprocessorbrand'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='operation_system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_shared.operationsystem'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='processor_frequency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_shared.processorfrequency'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='touch_screen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_notebook_reference.touchscreen'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='video_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_notebook_reference.videocard'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='video_processor_family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_shared.videoprocessorfamily'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='vr_support',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_notebook_reference.vrsupport'),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='case_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_shared.casematerial'),
        ),
    ]
