# Generated by Django 4.1 on 2024-12-19 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference_shared', '0020_rename_webcamerashutter_webcamshutter'),
        ('app_notebook_reference', '0005_notebookprocessorcoreqnty'),
        ('app_products', '0027_notebook_marketing_colour_notebook_nb_colour_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebook',
            name='keyboard_layout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_shared.keyboardlayout'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='keyboard_lightning',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_notebook_reference.keyboardlightning'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='mac_os_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_shared.macosversion'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='mobile_comms_module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_notebook_reference.mobilecommsmodule'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='nb_matrix_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_shared.notebookmatrixtype'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='windwos_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_shared.windowsversion'),
        ),
    ]
