# Generated by Django 4.1 on 2024-09-21 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference_shared', '0016_name'),
        ('app_products', '0028_remove_smartphone_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartphone',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_shared.name'),
        ),
    ]
