# Generated by Django 4.1 on 2024-09-21 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0029_smartphone_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartphone',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
