# Generated by Django 4.1 on 2024-12-21 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0029_notebook_key_word_notebook_nb_battery_capacity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notebook',
            old_name='windwos_version',
            new_name='windows_version',
        ),
    ]
