# Generated by Django 4.1 on 2024-09-21 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference_shared', '0017_description'),
        ('app_products', '0032_remove_smartphone_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartphone',
            name='description',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_shared.description'),
        ),
    ]
