# Generated by Django 4.1 on 2024-09-21 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0034_remove_smartphone_marketing_text_smartphone_key_word'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smartphone',
            name='card_max_volume',
        ),
    ]
