# Generated by Django 4.1 on 2025-01-06 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference_shared', '0022_audiodecoder_audiosystempower_hdmiversion_height_and_more'),
        ('app_products', '0035_remove_notebook_battery_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tv',
            name='tv_tuner',
            field=models.ManyToManyField(blank=True, to='app_reference_shared.tvtuner'),
        ),
    ]
