# Generated by Django 4.1 on 2024-09-21 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference_smartphones', '0006_brand_is_collection_caseform_is_collection_and_more'),
        ('app_products', '0036_smartphone_max_card_volume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smartphone',
            name='gadget_model',
        ),
        migrations.AddField(
            model_name='smartphone',
            name='gadget_model',
            field=models.ManyToManyField(blank=True, to='app_reference_smartphones.gadgetmodel'),
        ),
    ]
