# Generated by Django 4.1 on 2025-01-08 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference_shared', '0025_activecooling_additionalpowersupplyconnector_bustype_and_more'),
        ('app_videocard_reference', '0001_initial'),
        ('app_products', '0036_alter_tv_tv_tuner'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoCardProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('video_url', models.URLField(blank=True)),
                ('image_1', models.URLField(blank=True)),
                ('image_2', models.URLField(blank=True)),
                ('image_3', models.URLField(blank=True)),
                ('image_4', models.URLField(blank=True)),
                ('image_5', models.URLField(blank=True)),
                ('VGA_connector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_shared.vgaconnector')),
                ('active_cooling', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_shared.activecooling')),
                ('additional_power_supply_connector', models.ManyToManyField(blank=True, to='app_reference_shared.additionalpowersupplyconnector')),
                ('brand_video_card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_videocard_reference.videocardbrand')),
                ('bus_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_shared.bustype')),
                ('category_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_shared.ozoncategory')),
                ('cooling_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_shared.coolingtype')),
                ('country_of_manufacture', models.ManyToManyField(blank=True, to='app_reference_shared.countryofmanufacture')),
                ('description', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_shared.description')),
                ('dvi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_shared.dvi')),
                ('graphics_processor_frequency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_shared.graphicsprocessorfrequency')),
                ('length', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_shared.length')),
                ('lhr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_shared.lhr')),
                ('life_span', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_shared.lifespan')),
                ('max_resolution', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_shared.maxresolution')),
                ('model_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_shared.modelname')),
                ('module_height', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_shared.moduleheight')),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_shared.name')),
                ('number_of_fans', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_videocard_reference.numberoffans')),
                ('number_of_slots', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_videocard_reference.numberofslots')),
                ('number_of_supported_monitors', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_shared.numberofsupportedmonitors')),
                ('number_of_universal_processors', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_shared.numberofuniversalprocessors')),
                ('part_number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_shared.partnumber')),
                ('product_set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_shared.productset')),
                ('raster_block', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_shared.rasterblock')),
                ('recommended_power_supply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_shared.recommendedpowersupply')),
                ('shader_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_shared.shaderversion')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_shared.size')),
                ('storage_bus_frequency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_shared.storagebusfrequency')),
                ('storage_bus_width', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_shared.storagebuswidth')),
                ('supported_api', models.ManyToManyField(blank=True, to='app_reference_shared.supportedapi')),
                ('technology', models.ManyToManyField(blank=True, to='app_reference_shared.technology')),
                ('texture_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_shared.textureunit')),
                ('tv_power_consumption', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_shared.powerconsumption')),
                ('type_video_card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_videocard_reference.typevideocard')),
                ('video_card_colour', models.ManyToManyField(blank=True, to='app_videocard_reference.videocardcolour')),
                ('video_card_display_port', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_shared.videocarddisplayport')),
                ('video_card_hdmi_connector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_shared.videocardhdmiconnector')),
                ('video_card_interface', models.ManyToManyField(blank=True, to='app_videocard_reference.videocardinterface')),
                ('video_card_processor_brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_shared.videocardprocessorbrand')),
                ('video_card_processor_family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_shared.videocardprocessorfamily')),
                ('video_card_storage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_videocard_reference.videocardstorage')),
                ('video_card_storage_type', models.ManyToManyField(blank=True, to='app_videocard_reference.videocardstoragetype')),
                ('video_processor_max_frequency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_shared.videoprocessormaxfrequency')),
                ('warranty_period', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_shared.warrantyperiod')),
                ('weight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_shared.weight')),
            ],
        ),
    ]
