# Generated by Django 4.1 on 2024-09-21 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference_smartphones', '0006_brand_is_collection_caseform_is_collection_and_more'),
        ('app_products', '0037_remove_smartphone_gadget_model_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smartphone',
            name='protection_grade',
        ),
        migrations.AddField(
            model_name='smartphone',
            name='protection_grade',
            field=models.ManyToManyField(blank=True, to='app_reference_smartphones.protectiongrade'),
        ),
    ]
