# Generated by Django 4.1 on 2024-09-21 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference_shared', '0019_maxcardvolume'),
        ('app_products', '0038_remove_smartphone_protection_grade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smartphone',
            name='hazard_grade',
        ),
        migrations.AddField(
            model_name='smartphone',
            name='hazard_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_reference_shared.hazardgrade'),
        ),
    ]
