# Generated by Django 4.1 on 2024-09-21 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference_shared', '0019_maxcardvolume'),
        ('app_products', '0039_remove_smartphone_hazard_grade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smartphone',
            name='interface',
        ),
        migrations.AddField(
            model_name='smartphone',
            name='interface',
            field=models.ManyToManyField(blank=True, to='app_reference_shared.interface'),
        ),
    ]
