# Generated by Django 4.1 on 2024-09-24 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0041_alter_smartphone_part_number_alter_smartphone_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smartphone',
            name='euro_asian_code',
        ),
        migrations.RemoveField(
            model_name='smartphone',
            name='seller_code',
        ),
    ]
