# Generated by Django 4.1 on 2024-09-24 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference_shared', '0031_cardtitlemodelname'),
        ('app_products', '0043_remove_smartphone_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartphone',
            name='card_title_model_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_shared.cardtitlemodelname'),
        ),
    ]
