# Generated by Django 4.1 on 2024-09-24 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference_shared', '0030_onetagmodelname'),
        ('app_products', '0043_remove_smartphone_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartphone',
            name='model_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_shared.onetagmodelname'),
        ),
    ]
