# Generated by Django 4.1 on 2024-09-27 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_monitor_reference', '0001_initial'),
        ('app_reference_smartphones', '0008_rename_type_typesmartphone'),
        ('app_reference_shared', '0032_lightningtype'),
        ('app_products', '0047_alter_smartphone_image_1_alter_smartphone_image_2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('image_1', models.URLField(blank=True)),
                ('image_2', models.URLField(blank=True)),
                ('image_3', models.URLField(blank=True)),
                ('image_4', models.URLField(blank=True)),
                ('image_5', models.URLField(blank=True)),
                ('authentification', models.ManyToManyField(blank=True, to='app_reference_shared.authentication')),
                ('basic_camera_resolution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_shared.basiccamerresolution')),
                ('bluetooth', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_reference_shared.bluetoothtype')),
                ('camera_function', models.ManyToManyField(blank=True, to='app_reference_shared.camerafunction')),
                ('card_title_model_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_shared.cardtitlemodelname')),
                ('case_form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_reference_smartphones.caseform')),
                ('case_material', models.ManyToManyField(blank=True, to='app_reference_shared.casematerial')),
                ('category_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_shared.ozoncategory')),
                ('colour', models.ManyToManyField(blank=True, to='app_reference_smartphones.colour')),
                ('country_of_manufacture', models.ManyToManyField(blank=True, to='app_reference_shared.countryofmanufacture')),
                ('description', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_shared.description')),
                ('front_camera_resolution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_shared.frontcamerresolution')),
                ('gadget_model', models.ManyToManyField(blank=True, to='app_reference_smartphones.gadgetmodel')),
                ('gadget_serie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_reference_shared.gadgetserie')),
                ('hazard_grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_reference_shared.hazardgrade')),
                ('interface', models.ManyToManyField(blank=True, to='app_reference_shared.interface')),
                ('key_word', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_shared.keyword')),
                ('life_span', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_shared.lifespan')),
                ('lighting_type', models.ManyToManyField(blank=True, to='app_reference_shared.lightningtype')),
                ('marketing_colour', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_shared.marketingcolour')),
                ('matrix_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_reference_shared.matrixtype')),
                ('model_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_shared.modelname')),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_shared.name')),
                ('navigation', models.ManyToManyField(blank=True, to='app_reference_shared.navigationtype')),
                ('part_number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_shared.partnumber')),
                ('product_set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_shared.productset')),
                ('protection_grade', models.ManyToManyField(blank=True, to='app_reference_smartphones.protectiongrade')),
                ('publishing_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_reference_shared.publishingyear')),
                ('qnty_of_basic_cameras', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_reference_smartphones.qntyofbasiccamera')),
                ('record_max_speed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_shared.recordmaxspeed')),
                ('resolution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_monitor_reference.resolution')),
                ('screen_resolution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_reference_smartphones.screenresolution')),
                ('screen_size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_shared.screensize')),
                ('sensor', models.ManyToManyField(blank=True, to='app_reference_shared.sensor')),
                ('sim_card_qnty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_reference_smartphones.simcardqnty')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_shared.size')),
                ('smartphone_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_reference_shared.smartphoneversion')),
                ('special_feature', models.ManyToManyField(blank=True, to='app_reference_shared.specialfeature')),
                ('stabilization', models.ManyToManyField(blank=True, to='app_reference_shared.stabilization')),
                ('standby_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_shared.standbyperiod')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_monitor_reference.typemonitor')),
                ('video_quality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_reference_smartphones.videoquality')),
                ('warranty_period', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_shared.warrantyperiod')),
                ('weight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_shared.weight')),
                ('wifi', models.ManyToManyField(blank=True, to='app_reference_shared.wifitype')),
                ('wireless_interface', models.ManyToManyField(blank=True, to='app_reference_shared.wirelessinterface')),
                ('work_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_shared.workperiod')),
            ],
            options={
                'verbose_name': 'smartphone',
                'verbose_name_plural': 'smartphones',
            },
        ),
    ]
