# Generated by Django 4.1 on 2024-09-27 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference_shared', '0036_adjustment'),
        ('app_products', '0048_monitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='adjusments',
            field=models.ManyToManyField(blank=True, to='app_reference_shared.adjustment'),
        ),
        migrations.AddField(
            model_name='monitor',
            name='hdmi_ports',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_shared.hdmiports'),
        ),
        migrations.AddField(
            model_name='monitor',
            name='screen_coating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_shared.screencoating'),
        ),
    ]
