# Generated by Django 4.1 on 2024-09-27 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference_shared', '0037_pixelsize'),
        ('app_products', '0049_monitor_adjusments_monitor_hdmi_ports_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='pixel_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_shared.pixelsize'),
        ),
    ]
