# Generated by Django 4.1 on 2024-09-27 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference_shared', '0038_ratio'),
        ('app_products', '0050_monitor_pixel_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='ratio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_shared.ratio'),
        ),
    ]
