# Generated by Django 4.1 on 2024-09-27 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference_shared', '0039_maxscreenfrequency'),
        ('app_products', '0051_monitor_ratio'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='max_screen_frq',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_shared.maxscreenfrequency'),
        ),
    ]
