# Generated by Django 4.1 on 2024-09-27 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference_shared', '0041_contrast'),
        ('app_products', '0053_monitor_brightness'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='contrast',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_shared.contrast'),
        ),
    ]
