# Generated by Django 4.1 on 2024-09-27 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference_shared', '0042_dynamiccontrast_lookangle'),
        ('app_products', '0054_monitor_contrast'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='dynamic_contrast',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_shared.dynamiccontrast'),
        ),
        migrations.AddField(
            model_name='monitor',
            name='look_angle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_shared.lookangle'),
        ),
    ]
