# Generated by Django 4.1 on 2024-09-27 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference_shared', '0043_horizontalfrequency_verticalfrequency'),
        ('app_products', '0055_monitor_dynamic_contrast_monitor_look_angle'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='horizontal_frequency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_shared.horizontalfrequency'),
        ),
        migrations.AddField(
            model_name='monitor',
            name='vertical_frequency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_shared.verticalfrequency'),
        ),
    ]
