# Generated by Django 4.1 on 2024-09-27 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference_shared', '0044_standadjustment_webcamera'),
        ('app_products', '0056_monitor_horizontal_frequency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='stand_adjustment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_shared.standadjustment'),
        ),
        migrations.AddField(
            model_name='monitor',
            name='web_camera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_shared.webcamera'),
        ),
    ]
