# Generated by Django 4.1 on 2024-09-27 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference_shared', '0047_pixelperinch'),
        ('app_monitor_reference', '0004_builtinspeaker_alter_usbport_is_collection_and_more'),
        ('app_products', '0059_monitor_vesa_fixture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitor',
            name='sim_card_qnty',
        ),
        migrations.AddField(
            model_name='monitor',
            name='builtin_speaker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_monitor_reference.builtinspeaker'),
        ),
        migrations.AddField(
            model_name='monitor',
            name='pixel_per_inch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_shared.pixelperinch'),
        ),
    ]
