# Generated by Django 4.1 on 2024-09-27 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference_shared', '0049_designfeature'),
        ('app_monitor_reference', '0005_curveddispaly'),
        ('app_products', '0061_monitor_monitor_installation'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='curved_display',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_monitor_reference.curveddispaly'),
        ),
        migrations.AddField(
            model_name='monitor',
            name='design_feature',
            field=models.ManyToManyField(blank=True, to='app_reference_shared.designfeature'),
        ),
    ]
