# Generated by Django 4.1 on 2024-09-27 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference_shared', '0051_monitormatrix'),
        ('app_products', '0063_monitor_response_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='monitor_matrix',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_shared.monitormatrix'),
        ),
    ]
