# Generated by Django 4.1 on 2024-09-27 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference_shared', '0052_monitorapplication'),
        ('app_products', '0064_monitor_monitor_matrix'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='monitor_application',
            field=models.ManyToManyField(blank=True, to='app_reference_shared.monitorapplication'),
        ),
    ]
