# Generated by Django 4.1 on 2024-09-27 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference_shared', '0053_monitorconnector'),
        ('app_products', '0065_monitor_monitor_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='monitor_connector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference_shared.monitorconnector'),
        ),
    ]
