# Generated by Django 4.1 on 2024-09-27 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_monitor_reference', '0006_hdr'),
        ('app_products', '0066_monitor_monitor_connector'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='hdr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_monitor_reference.hdr'),
        ),
    ]
