# Generated by Django 4.1 on 2024-09-27 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference_shared', '0054_hdrstandard'),
        ('app_products', '0067_monitor_hdr'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='hdr_standard',
            field=models.ManyToManyField(blank=True, to='app_reference_shared.hdrstandard'),
        ),
    ]
