# Generated by Django 4.1 on 2024-09-28 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0068_monitor_hdr_standard'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monitor',
            options={'verbose_name': 'monitor', 'verbose_name_plural': 'monitors'},
        ),
        migrations.RemoveField(
            model_name='monitor',
            name='authentification',
        ),
        migrations.RemoveField(
            model_name='monitor',
            name='basic_camera_resolution',
        ),
        migrations.RemoveField(
            model_name='monitor',
            name='bluetooth',
        ),
        migrations.RemoveField(
            model_name='monitor',
            name='camera_function',
        ),
        migrations.RemoveField(
            model_name='monitor',
            name='case_form',
        ),
        migrations.RemoveField(
            model_name='monitor',
            name='case_material',
        ),
        migrations.RemoveField(
            model_name='monitor',
            name='front_camera_resolution',
        ),
        migrations.RemoveField(
            model_name='monitor',
            name='gadget_model',
        ),
        migrations.RemoveField(
            model_name='monitor',
            name='hazard_grade',
        ),
        migrations.RemoveField(
            model_name='monitor',
            name='interface',
        ),
        migrations.RemoveField(
            model_name='monitor',
            name='marketing_colour',
        ),
        migrations.RemoveField(
            model_name='monitor',
            name='matrix_type',
        ),
        migrations.RemoveField(
            model_name='monitor',
            name='navigation',
        ),
        migrations.RemoveField(
            model_name='monitor',
            name='protection_grade',
        ),
        migrations.RemoveField(
            model_name='monitor',
            name='publishing_year',
        ),
        migrations.RemoveField(
            model_name='monitor',
            name='qnty_of_basic_cameras',
        ),
        migrations.RemoveField(
            model_name='monitor',
            name='record_max_speed',
        ),
        migrations.RemoveField(
            model_name='monitor',
            name='screen_resolution',
        ),
        migrations.RemoveField(
            model_name='monitor',
            name='sensor',
        ),
        migrations.RemoveField(
            model_name='monitor',
            name='smartphone_version',
        ),
        migrations.RemoveField(
            model_name='monitor',
            name='stabilization',
        ),
        migrations.RemoveField(
            model_name='monitor',
            name='standby_period',
        ),
        migrations.RemoveField(
            model_name='monitor',
            name='video_quality',
        ),
        migrations.RemoveField(
            model_name='monitor',
            name='wifi',
        ),
        migrations.RemoveField(
            model_name='monitor',
            name='wireless_interface',
        ),
        migrations.RemoveField(
            model_name='monitor',
            name='work_period',
        ),
    ]
