# Generated by Django 4.1 on 2024-10-05 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_monitor_reference', '0010_rename_monitorbrand_brandmonitor_and_more'),
        ('app_products', '0070_remove_monitor_monitor_connector_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitor',
            name='colour',
        ),
        migrations.AddField(
            model_name='monitor',
            name='brand_monitor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_monitor_reference.brandmonitor'),
        ),
        migrations.AddField(
            model_name='monitor',
            name='colour_monitor',
            field=models.ManyToManyField(blank=True, to='app_monitor_reference.colourmonitor'),
        ),
    ]
