# Generated by Django 4.1 on 2024-10-05 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_monitor_reference', '0011_euroasiancodemonitor'),
        ('app_products', '0071_remove_monitor_colour_monitor_brand_monitor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartphone',
            name='euro_asian_code_monitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_monitor_reference.euroasiancodemonitor'),
        ),
    ]
