# Generated by Django 4.1 on 2024-10-05 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0072_smartphone_euro_asian_code_monitor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monitor',
            old_name='adjusments',
            new_name='adjustments',
        ),
    ]
