# Generated by Django 4.1 on 2024-10-05 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference_shared', '0055_alter_specialfeature_attribute_id_and_more'),
        ('app_products', '0073_rename_adjusments_monitor_adjustments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitor',
            name='monitor_installation',
        ),
        migrations.AddField(
            model_name='monitor',
            name='monitor_installation',
            field=models.ManyToManyField(blank=True, to='app_reference_shared.monitorinstallation'),
        ),
    ]
