# Generated by Django 4.1 on 2024-09-17 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AndroidVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_name', models.CharField(max_length=50, null=True)),
                ('attribute_id', models.CharField(max_length=50, null=True)),
                ('name', models.CharField(max_length=100)),
                ('digital_code', models.CharField(max_length=20)),
                ('is_required', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Authentication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_name', models.CharField(max_length=50, null=True)),
                ('attribute_id', models.CharField(max_length=50, null=True)),
                ('name', models.CharField(max_length=100)),
                ('digital_code', models.CharField(max_length=20)),
                ('is_required', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='BluetoothType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_name', models.CharField(max_length=50, null=True)),
                ('attribute_id', models.CharField(max_length=50, null=True)),
                ('name', models.CharField(max_length=100)),
                ('digital_code', models.CharField(max_length=20)),
                ('is_required', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CameraFunction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_name', models.CharField(max_length=50, null=True)),
                ('attribute_id', models.CharField(max_length=50, null=True)),
                ('name', models.CharField(max_length=100)),
                ('digital_code', models.CharField(max_length=20)),
                ('is_required', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CardType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_name', models.CharField(max_length=50, null=True)),
                ('attribute_id', models.CharField(max_length=50, null=True)),
                ('name', models.CharField(max_length=100)),
                ('digital_code', models.CharField(max_length=20)),
                ('is_required', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CaseMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_name', models.CharField(max_length=50, null=True)),
                ('attribute_id', models.CharField(max_length=50, null=True)),
                ('name', models.CharField(max_length=100)),
                ('digital_code', models.CharField(max_length=20)),
                ('is_required', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ChargingFunction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_name', models.CharField(max_length=50, null=True)),
                ('attribute_id', models.CharField(max_length=50, null=True)),
                ('name', models.CharField(max_length=100)),
                ('digital_code', models.CharField(max_length=20)),
                ('is_required', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CommunicationStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_name', models.CharField(max_length=50, null=True)),
                ('attribute_id', models.CharField(max_length=50, null=True)),
                ('name', models.CharField(max_length=100)),
                ('digital_code', models.CharField(max_length=20)),
                ('is_required', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CountryOfManufacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_name', models.CharField(max_length=50, null=True)),
                ('attribute_id', models.CharField(max_length=50, null=True)),
                ('name', models.CharField(max_length=100)),
                ('digital_code', models.CharField(max_length=20)),
                ('is_required', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ESimSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_name', models.CharField(max_length=50, null=True)),
                ('attribute_id', models.CharField(max_length=50, null=True)),
                ('name', models.CharField(max_length=100)),
                ('digital_code', models.CharField(max_length=20)),
                ('is_required', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='GadgetSerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_name', models.CharField(max_length=50, null=True)),
                ('attribute_id', models.CharField(max_length=50, null=True)),
                ('name', models.CharField(max_length=100)),
                ('digital_code', models.CharField(max_length=20)),
                ('is_required', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='HardDrive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_name', models.CharField(max_length=50, null=True)),
                ('attribute_id', models.CharField(max_length=50, null=True)),
                ('name', models.CharField(max_length=100)),
                ('digital_code', models.CharField(max_length=20)),
                ('is_required', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='HazardGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_name', models.CharField(max_length=50, null=True)),
                ('attribute_id', models.CharField(max_length=50, null=True)),
                ('name', models.CharField(max_length=100)),
                ('digital_code', models.CharField(max_length=20)),
                ('is_required', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_name', models.CharField(max_length=50, null=True)),
                ('attribute_id', models.CharField(max_length=50, null=True)),
                ('name', models.CharField(max_length=100)),
                ('digital_code', models.CharField(max_length=20)),
                ('is_required', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='IOSVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_name', models.CharField(max_length=50, null=True)),
                ('attribute_id', models.CharField(max_length=50, null=True)),
                ('name', models.CharField(max_length=100)),
                ('digital_code', models.CharField(max_length=20)),
                ('is_required', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MatrixType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_name', models.CharField(max_length=50, null=True)),
                ('attribute_id', models.CharField(max_length=50, null=True)),
                ('name', models.CharField(max_length=100)),
                ('digital_code', models.CharField(max_length=20)),
                ('is_required', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ModelName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_name', models.CharField(max_length=50, null=True)),
                ('attribute_id', models.CharField(max_length=50, null=True)),
                ('name', models.CharField(max_length=100)),
                ('digital_code', models.CharField(max_length=20)),
                ('is_required', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='NavigationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_name', models.CharField(max_length=50, null=True)),
                ('attribute_id', models.CharField(max_length=50, null=True)),
                ('name', models.CharField(max_length=100)),
                ('digital_code', models.CharField(max_length=20)),
                ('is_required', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='OperationSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_name', models.CharField(max_length=50, null=True)),
                ('attribute_id', models.CharField(max_length=50, null=True)),
                ('name', models.CharField(max_length=100)),
                ('digital_code', models.CharField(max_length=20)),
                ('is_required', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='OzonCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=100, null=True)),
                ('type_id', models.CharField(max_length=50, null=True)),
                ('description_category_id', models.CharField(max_length=80, null=True)),
                ('category_name', models.CharField(max_length=80, null=True)),
                ('group_description_category_id', models.CharField(max_length=80, null=True)),
                ('group_category_name', models.CharField(max_length=80, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessorBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_name', models.CharField(max_length=50, null=True)),
                ('attribute_id', models.CharField(max_length=50, null=True)),
                ('name', models.CharField(max_length=100)),
                ('digital_code', models.CharField(max_length=20)),
                ('is_required', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_name', models.CharField(max_length=50, null=True)),
                ('attribute_id', models.CharField(max_length=50, null=True)),
                ('name', models.CharField(max_length=100)),
                ('digital_code', models.CharField(max_length=20)),
                ('is_required', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PublishingYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_name', models.CharField(max_length=50, null=True)),
                ('attribute_id', models.CharField(max_length=50, null=True)),
                ('name', models.CharField(max_length=100)),
                ('digital_code', models.CharField(max_length=20)),
                ('is_required', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RAM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_name', models.CharField(max_length=50, null=True)),
                ('attribute_id', models.CharField(max_length=50, null=True)),
                ('name', models.CharField(max_length=100)),
                ('digital_code', models.CharField(max_length=20)),
                ('is_required', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_name', models.CharField(max_length=50, null=True)),
                ('attribute_id', models.CharField(max_length=50, null=True)),
                ('name', models.CharField(max_length=100)),
                ('digital_code', models.CharField(max_length=20)),
                ('is_required', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SimType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_name', models.CharField(max_length=50, null=True)),
                ('attribute_id', models.CharField(max_length=50, null=True)),
                ('name', models.CharField(max_length=100)),
                ('digital_code', models.CharField(max_length=20)),
                ('is_required', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SmartphoneVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_name', models.CharField(max_length=50, null=True)),
                ('attribute_id', models.CharField(max_length=50, null=True)),
                ('name', models.CharField(max_length=100)),
                ('digital_code', models.CharField(max_length=20)),
                ('is_required', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SpecialFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_name', models.CharField(max_length=50, null=True)),
                ('attribute_id', models.CharField(max_length=50, null=True)),
                ('name', models.CharField(max_length=100)),
                ('digital_code', models.CharField(max_length=20)),
                ('is_required', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Stabilization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_name', models.CharField(max_length=50, null=True)),
                ('attribute_id', models.CharField(max_length=50, null=True)),
                ('name', models.CharField(max_length=100)),
                ('digital_code', models.CharField(max_length=20)),
                ('is_required', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='VideoProcessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_name', models.CharField(max_length=50, null=True)),
                ('attribute_id', models.CharField(max_length=50, null=True)),
                ('name', models.CharField(max_length=100)),
                ('digital_code', models.CharField(max_length=20)),
                ('is_required', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='VideoProcessorBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_name', models.CharField(max_length=50, null=True)),
                ('attribute_id', models.CharField(max_length=50, null=True)),
                ('name', models.CharField(max_length=100)),
                ('digital_code', models.CharField(max_length=20)),
                ('is_required', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='WarrantyPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_name', models.CharField(max_length=50, null=True)),
                ('attribute_id', models.CharField(max_length=50, null=True)),
                ('name', models.CharField(max_length=100)),
                ('digital_code', models.CharField(max_length=20)),
                ('is_required', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='WifiType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_name', models.CharField(max_length=50, null=True)),
                ('attribute_id', models.CharField(max_length=50, null=True)),
                ('name', models.CharField(max_length=100)),
                ('digital_code', models.CharField(max_length=20)),
                ('is_required', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='WirelessInterface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_name', models.CharField(max_length=50, null=True)),
                ('attribute_id', models.CharField(max_length=50, null=True)),
                ('name', models.CharField(max_length=100)),
                ('digital_code', models.CharField(max_length=20)),
                ('is_required', models.BooleanField(default=False)),
            ],
        ),
    ]
