# Generated by Django 4.1 on 2024-10-18 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference_shared', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ozoncategory',
            name='activated',
            field=models.BooleanField(null=True),
        ),
    ]
