# Generated by Django 4.1 on 2024-10-18 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference_shared', '0002_ozoncategory_activated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ozoncategory',
            name='activated',
            field=models.BooleanField(default=False),
        ),
    ]
