# Generated by Django 4.1 on 2024-11-15 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference_shared', '0003_alter_ozoncategory_activated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelname',
            name='value',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='name',
            name='value',
            field=models.CharField(blank=True, max_length=70),
        ),
    ]
