# Generated by Django 4.1 on 2024-11-15 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference_shared', '0004_alter_modelname_value_alter_name_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='name',
            name='value',
            field=models.CharField(blank=True, max_length=75),
        ),
    ]
