# Generated by Django 4.1 on 2024-09-17 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference_shared', '0005_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weight',
            name='attribute_id',
            field=models.CharField(default='4383', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='weight',
            name='attribute_name',
            field=models.CharField(default='Вес товара, г', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='weight',
            name='digital_code',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='weight',
            name='is_required',
            field=models.BooleanField(default=False),
        ),
    ]
