# Generated by Django 4.1 on 2024-11-29 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference_shared', '0005_alter_name_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelname',
            name='equipment_brand',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='modelname',
            name='equipment_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
