# Generated by Django 4.1 on 2024-09-17 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference_shared', '0006_alter_weight_attribute_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnumber',
            name='attribute_id',
            field=models.CharField(default='4381', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='partnumber',
            name='attribute_name',
            field=models.CharField(default='Партномер', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='partnumber',
            name='digital_code',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
