# Generated by Django 4.1 on 2024-12-01 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference_shared', '0007_alter_productset_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standadjustment',
            name='value',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
