# Generated by Django 4.1 on 2024-09-17 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference_shared', '0007_alter_partnumber_attribute_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='attribute_id',
            field=models.CharField(default='4382', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='size',
            name='attribute_name',
            field=models.CharField(default='Размеры, мм', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='size',
            name='digital_code',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='size',
            name='is_required',
            field=models.BooleanField(default=False),
        ),
    ]
