# Generated by Django 4.1 on 2024-09-17 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference_shared', '0008_alter_size_attribute_id_alter_size_attribute_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrontCamerResolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_name', models.CharField(default='Разрешение фронтальной (селфи) камеры, Мпикс', max_length=50, null=True)),
                ('attribute_id', models.CharField(default='4421', max_length=50, null=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('digital_code', models.CharField(default='0', max_length=20)),
                ('is_required', models.BooleanField(default=False)),
                ('category_dependent', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProductSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_name', models.CharField(default='Комплектация', max_length=50, null=True)),
                ('attribute_id', models.CharField(default='4384', max_length=50, null=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('digital_code', models.CharField(default='0', max_length=20)),
                ('is_required', models.BooleanField(default=False)),
                ('category_dependent', models.BooleanField(default=False)),
            ],
        ),
    ]
