# Generated by Django 4.1 on 2024-09-17 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference_shared', '0009_frontcamerresolution_productset'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicCamerResolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_name', models.CharField(default='Разрешение основной камеры, Мпикс', max_length=50, null=True)),
                ('attribute_id', models.CharField(default='4422', max_length=50, null=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('digital_code', models.CharField(default='0', max_length=20)),
                ('is_required', models.BooleanField(default=False)),
                ('category_dependent', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='BatteryCapacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_name', models.CharField(default='Емкость аккумулятора, мАч', max_length=50, null=True)),
                ('attribute_id', models.CharField(default='4429', max_length=50, null=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('digital_code', models.CharField(default='0', max_length=20)),
                ('is_required', models.BooleanField(default=False)),
                ('category_dependent', models.BooleanField(default=False)),
            ],
        ),
    ]
