# Generated by Django 4.1 on 2024-12-18 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference_shared', '0010_batterytype_builtindevice_cardreader_casecoating_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotebookProcessorBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_name', models.CharField(default='Бренд процессора', max_length=50)),
                ('attribute_id', models.CharField(default='11362', max_length=50, null=True)),
                ('value', models.CharField(blank=True, max_length=100)),
                ('dictionary_value_id', models.CharField(default=1, max_length=20)),
                ('is_required', models.BooleanField(default=False)),
                ('category_dependent', models.BooleanField(default=False)),
                ('is_collection', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='NotebookVideoProcessorBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_name', models.CharField(default='Бренд процессора', max_length=50)),
                ('attribute_id', models.CharField(default='11363', max_length=50, null=True)),
                ('value', models.CharField(blank=True, max_length=100)),
                ('dictionary_value_id', models.CharField(default=1, max_length=20)),
                ('is_required', models.BooleanField(default=False)),
                ('category_dependent', models.BooleanField(default=False)),
                ('is_collection', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='OperationSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_name', models.CharField(default='Операционная система', max_length=50)),
                ('attribute_id', models.CharField(default='11377', max_length=50, null=True)),
                ('value', models.CharField(blank=True, max_length=100)),
                ('dictionary_value_id', models.CharField(default=1, max_length=20)),
                ('is_required', models.BooleanField(default=False)),
                ('category_dependent', models.BooleanField(default=False)),
                ('is_collection', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='casematerial',
            name='attribute_id',
            field=models.CharField(default='10746', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='casematerial',
            name='attribute_name',
            field=models.CharField(default='Основной материал корпуса', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='osmobile',
            name='attribute_id',
            field=models.CharField(default='10889', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='osmobile',
            name='attribute_name',
            field=models.CharField(default='Операционная система', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='processorbrand',
            name='attribute_id',
            field=models.CharField(default='10315', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='processorbrand',
            name='attribute_name',
            field=models.CharField(default='Бренд процессора', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='videoprocessorbrand',
            name='attribute_id',
            field=models.CharField(default='5142', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='videoprocessorbrand',
            name='attribute_name',
            field=models.CharField(default='Бренд графического процессора', max_length=50, null=True),
        ),
    ]
