# Generated by Django 4.1 on 2024-09-17 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference_shared', '0011_standbyperiod_workperiod'),
    ]

    operations = [
        migrations.CreateModel(
            name='LifeSpan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_name', models.CharField(default='Срок службы, лет', max_length=50, null=True)),
                ('attribute_id', models.CharField(default='5920', max_length=50, null=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('digital_code', models.CharField(default='0', max_length=20)),
                ('is_required', models.BooleanField(default=False)),
                ('category_dependent', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RecordMaxSpeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_name', models.CharField(default='Макс. скорость видеосъемки, кадр/с', max_length=50, null=True)),
                ('attribute_id', models.CharField(default='5920', max_length=50, null=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('digital_code', models.CharField(default='0', max_length=20)),
                ('is_required', models.BooleanField(default=False)),
                ('category_dependent', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ScreenSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_name', models.CharField(default='Диагональ экрана, дюймы', max_length=50, null=True)),
                ('attribute_id', models.CharField(default='8587', max_length=50, null=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('digital_code', models.CharField(default='0', max_length=20)),
                ('is_required', models.BooleanField(default=False)),
                ('category_dependent', models.BooleanField(default=False)),
            ],
        ),
    ]
