# Generated by Django 4.1 on 2024-09-17 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference_shared', '0012_lifespan_recordmaxspeed_screensize'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingColour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_name', models.CharField(default='Название цвета', max_length=50, null=True)),
                ('attribute_id', models.CharField(default='10097', max_length=50, null=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('digital_code', models.CharField(default='0', max_length=20)),
                ('is_required', models.BooleanField(default=False)),
                ('category_dependent', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessorFrequency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_name', models.CharField(default='Частота процессора, ГГц', max_length=50, null=True)),
                ('attribute_id', models.CharField(default='10317', max_length=50, null=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('digital_code', models.CharField(default='0', max_length=20)),
                ('is_required', models.BooleanField(default=False)),
                ('category_dependent', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SellerCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_name', models.CharField(default='Код продавца', max_length=50, null=True)),
                ('attribute_id', models.CharField(default='9024', max_length=50, null=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('digital_code', models.CharField(default='0', max_length=20)),
                ('is_required', models.BooleanField(default=False)),
                ('category_dependent', models.BooleanField(default=False)),
            ],
        ),
    ]
