# Generated by Django 4.1 on 2024-12-18 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference_shared', '0012_keyboardlayout_macosversion_notebookbatterycapacity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bluetoothtype',
            name='attribute_id',
            field=models.CharField(default='4414', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bluetoothtype',
            name='attribute_name',
            field=models.CharField(default='Модуль связи Bluetooth', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='countryofmanufacture',
            name='attribute_id',
            field=models.CharField(default='4389', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='countryofmanufacture',
            name='attribute_name',
            field=models.CharField(default='Страна-изготовитель', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='processormodel',
            name='attribute_id',
            field=models.CharField(default='10320', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='processormodel',
            name='attribute_name',
            field=models.CharField(default='Модель процессора', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='warrantyperiod',
            name='attribute_id',
            field=models.CharField(default='4385', max_length=50, null=True),
        ),
    ]
