# Generated by Django 4.1 on 2024-12-19 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference_shared', '0013_alter_bluetoothtype_attribute_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PortQntyHDMI',
        ),
    ]
