# Generated by Django 4.1 on 2024-09-19 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference_shared', '0013_marketingcolour_processorfrequency_sellercode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basiccamerresolution',
            old_name='name',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='batterycapacity',
            old_name='name',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='frontcamerresolution',
            old_name='name',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='lifespan',
            old_name='name',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='marketingcolour',
            old_name='name',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='partnumber',
            old_name='name',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='processorfrequency',
            old_name='name',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='productset',
            old_name='name',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='recordmaxspeed',
            old_name='name',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='screensize',
            old_name='name',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='sellercode',
            old_name='name',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='size',
            old_name='digital_code',
            new_name='dictionary_value_id',
        ),
        migrations.RenameField(
            model_name='size',
            old_name='name',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='standbyperiod',
            old_name='name',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='weight',
            old_name='name',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='workperiod',
            old_name='name',
            new_name='value',
        ),
        migrations.RemoveField(
            model_name='androidversion',
            name='digital_code',
        ),
        migrations.RemoveField(
            model_name='androidversion',
            name='name',
        ),
        migrations.RemoveField(
            model_name='authentication',
            name='digital_code',
        ),
        migrations.RemoveField(
            model_name='authentication',
            name='name',
        ),
        migrations.RemoveField(
            model_name='basiccamerresolution',
            name='digital_code',
        ),
        migrations.RemoveField(
            model_name='batterycapacity',
            name='digital_code',
        ),
        migrations.RemoveField(
            model_name='bluetoothtype',
            name='digital_code',
        ),
        migrations.RemoveField(
            model_name='bluetoothtype',
            name='name',
        ),
        migrations.RemoveField(
            model_name='camerafunction',
            name='digital_code',
        ),
        migrations.RemoveField(
            model_name='camerafunction',
            name='name',
        ),
        migrations.RemoveField(
            model_name='cardtype',
            name='digital_code',
        ),
        migrations.RemoveField(
            model_name='cardtype',
            name='name',
        ),
        migrations.RemoveField(
            model_name='casematerial',
            name='digital_code',
        ),
        migrations.RemoveField(
            model_name='casematerial',
            name='name',
        ),
        migrations.RemoveField(
            model_name='chargingfunction',
            name='digital_code',
        ),
        migrations.RemoveField(
            model_name='chargingfunction',
            name='name',
        ),
        migrations.RemoveField(
            model_name='communicationstandard',
            name='digital_code',
        ),
        migrations.RemoveField(
            model_name='communicationstandard',
            name='name',
        ),
        migrations.RemoveField(
            model_name='countryofmanufacture',
            name='digital_code',
        ),
        migrations.RemoveField(
            model_name='countryofmanufacture',
            name='name',
        ),
        migrations.RemoveField(
            model_name='esimsupport',
            name='digital_code',
        ),
        migrations.RemoveField(
            model_name='esimsupport',
            name='name',
        ),
        migrations.RemoveField(
            model_name='frontcamerresolution',
            name='digital_code',
        ),
        migrations.RemoveField(
            model_name='gadgetserie',
            name='digital_code',
        ),
        migrations.RemoveField(
            model_name='gadgetserie',
            name='name',
        ),
        migrations.RemoveField(
            model_name='harddrive',
            name='digital_code',
        ),
        migrations.RemoveField(
            model_name='harddrive',
            name='name',
        ),
        migrations.RemoveField(
            model_name='hazardgrade',
            name='digital_code',
        ),
        migrations.RemoveField(
            model_name='hazardgrade',
            name='name',
        ),
        migrations.RemoveField(
            model_name='interface',
            name='digital_code',
        ),
        migrations.RemoveField(
            model_name='interface',
            name='name',
        ),
        migrations.RemoveField(
            model_name='iosversion',
            name='digital_code',
        ),
        migrations.RemoveField(
            model_name='iosversion',
            name='name',
        ),
        migrations.RemoveField(
            model_name='lifespan',
            name='digital_code',
        ),
        migrations.RemoveField(
            model_name='marketingcolour',
            name='digital_code',
        ),
        migrations.RemoveField(
            model_name='matrixtype',
            name='digital_code',
        ),
        migrations.RemoveField(
            model_name='matrixtype',
            name='name',
        ),
        migrations.RemoveField(
            model_name='modelname',
            name='digital_code',
        ),
        migrations.RemoveField(
            model_name='modelname',
            name='name',
        ),
        migrations.RemoveField(
            model_name='navigationtype',
            name='digital_code',
        ),
        migrations.RemoveField(
            model_name='navigationtype',
            name='name',
        ),
        migrations.RemoveField(
            model_name='operationsystem',
            name='digital_code',
        ),
        migrations.RemoveField(
            model_name='operationsystem',
            name='name',
        ),
        migrations.RemoveField(
            model_name='partnumber',
            name='digital_code',
        ),
        migrations.RemoveField(
            model_name='processorbrand',
            name='digital_code',
        ),
        migrations.RemoveField(
            model_name='processorbrand',
            name='name',
        ),
        migrations.RemoveField(
            model_name='processorfrequency',
            name='digital_code',
        ),
        migrations.RemoveField(
            model_name='processormodel',
            name='digital_code',
        ),
        migrations.RemoveField(
            model_name='processormodel',
            name='name',
        ),
        migrations.RemoveField(
            model_name='productset',
            name='digital_code',
        ),
        migrations.RemoveField(
            model_name='publishingyear',
            name='digital_code',
        ),
        migrations.RemoveField(
            model_name='publishingyear',
            name='name',
        ),
        migrations.RemoveField(
            model_name='ram',
            name='digital_code',
        ),
        migrations.RemoveField(
            model_name='ram',
            name='name',
        ),
        migrations.RemoveField(
            model_name='recordmaxspeed',
            name='digital_code',
        ),
        migrations.RemoveField(
            model_name='screensize',
            name='digital_code',
        ),
        migrations.RemoveField(
            model_name='sellercode',
            name='digital_code',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='digital_code',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='name',
        ),
        migrations.RemoveField(
            model_name='simtype',
            name='digital_code',
        ),
        migrations.RemoveField(
            model_name='simtype',
            name='name',
        ),
        migrations.RemoveField(
            model_name='smartphoneversion',
            name='digital_code',
        ),
        migrations.RemoveField(
            model_name='smartphoneversion',
            name='name',
        ),
        migrations.RemoveField(
            model_name='specialfeature',
            name='digital_code',
        ),
        migrations.RemoveField(
            model_name='specialfeature',
            name='name',
        ),
        migrations.RemoveField(
            model_name='stabilization',
            name='digital_code',
        ),
        migrations.RemoveField(
            model_name='stabilization',
            name='name',
        ),
        migrations.RemoveField(
            model_name='standbyperiod',
            name='digital_code',
        ),
        migrations.RemoveField(
            model_name='videoprocessor',
            name='digital_code',
        ),
        migrations.RemoveField(
            model_name='videoprocessor',
            name='name',
        ),
        migrations.RemoveField(
            model_name='videoprocessorbrand',
            name='digital_code',
        ),
        migrations.RemoveField(
            model_name='videoprocessorbrand',
            name='name',
        ),
        migrations.RemoveField(
            model_name='warrantyperiod',
            name='digital_code',
        ),
        migrations.RemoveField(
            model_name='warrantyperiod',
            name='name',
        ),
        migrations.RemoveField(
            model_name='weight',
            name='digital_code',
        ),
        migrations.RemoveField(
            model_name='wifitype',
            name='digital_code',
        ),
        migrations.RemoveField(
            model_name='wifitype',
            name='name',
        ),
        migrations.RemoveField(
            model_name='wirelessinterface',
            name='digital_code',
        ),
        migrations.RemoveField(
            model_name='wirelessinterface',
            name='name',
        ),
        migrations.RemoveField(
            model_name='workperiod',
            name='digital_code',
        ),
        migrations.AddField(
            model_name='androidversion',
            name='dictionary_value_id',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='androidversion',
            name='value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='authentication',
            name='dictionary_value_id',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='authentication',
            name='value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='basiccamerresolution',
            name='dictionary_value_id',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='batterycapacity',
            name='dictionary_value_id',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='bluetoothtype',
            name='dictionary_value_id',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='bluetoothtype',
            name='value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='camerafunction',
            name='dictionary_value_id',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='camerafunction',
            name='value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cardtype',
            name='dictionary_value_id',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='cardtype',
            name='value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='casematerial',
            name='dictionary_value_id',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='casematerial',
            name='value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='chargingfunction',
            name='dictionary_value_id',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='chargingfunction',
            name='value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='communicationstandard',
            name='dictionary_value_id',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='communicationstandard',
            name='value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='countryofmanufacture',
            name='dictionary_value_id',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='countryofmanufacture',
            name='value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='esimsupport',
            name='dictionary_value_id',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='esimsupport',
            name='value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='frontcamerresolution',
            name='dictionary_value_id',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='gadgetserie',
            name='dictionary_value_id',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='gadgetserie',
            name='value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='harddrive',
            name='dictionary_value_id',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='harddrive',
            name='value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='hazardgrade',
            name='dictionary_value_id',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='hazardgrade',
            name='value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='interface',
            name='dictionary_value_id',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='interface',
            name='value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='iosversion',
            name='dictionary_value_id',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='iosversion',
            name='value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='lifespan',
            name='dictionary_value_id',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='marketingcolour',
            name='dictionary_value_id',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='matrixtype',
            name='dictionary_value_id',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='matrixtype',
            name='value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='modelname',
            name='dictionary_value_id',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='modelname',
            name='value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='navigationtype',
            name='dictionary_value_id',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='navigationtype',
            name='value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='operationsystem',
            name='dictionary_value_id',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='operationsystem',
            name='value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='partnumber',
            name='dictionary_value_id',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='processorbrand',
            name='dictionary_value_id',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='processorbrand',
            name='value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='processorfrequency',
            name='dictionary_value_id',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='processormodel',
            name='dictionary_value_id',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='processormodel',
            name='value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='productset',
            name='dictionary_value_id',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='publishingyear',
            name='dictionary_value_id',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='publishingyear',
            name='value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='ram',
            name='dictionary_value_id',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='ram',
            name='value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='recordmaxspeed',
            name='dictionary_value_id',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='screensize',
            name='dictionary_value_id',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='sellercode',
            name='dictionary_value_id',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='sensor',
            name='dictionary_value_id',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='sensor',
            name='value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='simtype',
            name='dictionary_value_id',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='simtype',
            name='value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='smartphoneversion',
            name='dictionary_value_id',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='smartphoneversion',
            name='value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='specialfeature',
            name='dictionary_value_id',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='specialfeature',
            name='value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='stabilization',
            name='dictionary_value_id',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='stabilization',
            name='value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='standbyperiod',
            name='dictionary_value_id',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='videoprocessor',
            name='dictionary_value_id',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='videoprocessor',
            name='value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='videoprocessorbrand',
            name='dictionary_value_id',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='videoprocessorbrand',
            name='value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='warrantyperiod',
            name='dictionary_value_id',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='warrantyperiod',
            name='value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='weight',
            name='dictionary_value_id',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='wifitype',
            name='dictionary_value_id',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='wifitype',
            name='value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='wirelessinterface',
            name='dictionary_value_id',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='wirelessinterface',
            name='value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='workperiod',
            name='dictionary_value_id',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
