# Generated by Django 4.1 on 2024-12-19 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference_shared', '0016_displayport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maxscreenfrequency',
            name='attribute_name',
            field=models.CharField(default='Макс. частота обновления, Гц', max_length=50),
        ),
    ]
