# Generated by Django 4.1 on 2024-12-19 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference_shared', '0018_rename_totalsddvolume_totalssdvolume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebookmatrixtype',
            name='attribute_id',
            field=models.CharField(default='11380', max_length=50, null=True),
        ),
    ]
