# Generated by Django 4.1 on 2024-12-19 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference_shared', '0019_alter_notebookmatrixtype_attribute_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WebCameraShutter',
            new_name='WebCamShutter',
        ),
    ]
