# Generated by Django 4.1 on 2024-09-21 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference_shared', '0020_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='json',
            name='attribute_name',
            field=models.CharField(default='Расширенное описание товара с фото и видео в формате JSON', max_length=100, null=True),
        ),
    ]
