# Generated by Django 4.1 on 2024-09-21 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference_shared', '0021_alter_json_attribute_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='json',
            name='attribute_name',
            field=models.CharField(default='Rich-контент JSON', max_length=100, null=True),
        ),
    ]
