# Generated by Django 4.1 on 2024-09-21 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference_shared', '0022_alter_json_attribute_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='json',
            name='value',
            field=models.TextField(blank=True),
        ),
    ]
