# Generated by Django 4.1 on 2025-01-06 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0036_alter_tv_tv_tuner'),
        ('app_reference_shared', '0022_audiodecoder_audiosystempower_hdmiversion_height_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TVPowerConsumption',
            new_name='PowerConsumption',
        ),
    ]
