# Generated by Django 4.1 on 2024-09-24 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0041_alter_smartphone_part_number_alter_smartphone_type'),
        ('app_reference_shared', '0023_alter_json_value'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RAM',
            new_name='RamSmartphone',
        ),
    ]
