# Generated by Django 4.1 on 2024-09-24 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0041_alter_smartphone_part_number_alter_smartphone_type'),
        ('app_reference_shared', '0024_rename_ram_ramsmartphone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OperationSystem',
            new_name='OSMobile',
        ),
    ]
