# Generated by Django 4.1 on 2024-09-24 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference_shared', '0026_alter_smartphoneversion_attribute_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartphoneversion',
            name='value',
            field=models.CharField(default='Ростест (ЕАС)', max_length=100),
        ),
    ]
