# Generated by Django 4.1 on 2024-09-24 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference_shared', '0027_alter_smartphoneversion_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartphoneversion',
            name='attribute_id',
            field=models.CharField(default='22975', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='smartphoneversion',
            name='attribute_name',
            field=models.CharField(default='Версия смартфона', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='smartphoneversion',
            name='dictionary_value_id',
            field=models.CharField(default='971992309', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='smartphoneversion',
            name='value',
            field=models.CharField(default='Ростест (ЕАС)', max_length=100, null=True),
        ),
    ]
