# Generated by Django 4.1 on 2024-09-24 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference_shared', '0028_alter_smartphoneversion_attribute_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warrantyperiod',
            name='attribute_id',
            field=models.CharField(default='9048', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='warrantyperiod',
            name='attribute_name',
            field=models.CharField(default='Гарантийный срок', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='warrantyperiod',
            name='value',
            field=models.CharField(default='1 год с момента покупки', max_length=100, null=True),
        ),
    ]
