# Generated by Django 4.1 on 2024-09-24 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0044_alter_smartphone_model_name'),
        ('app_reference_shared', '0030_onetagmodelname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModelName',
        ),
    ]
