# Generated by Django 4.1 on 2024-09-24 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0045_alter_smartphone_model_name'),
        ('app_reference_shared', '0032_modelname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OneTagModelName',
        ),
        migrations.AlterField(
            model_name='modelname',
            name='attribute_id',
            field=models.CharField(default='9048', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='modelname',
            name='attribute_name',
            field=models.CharField(default='Название модели (для объединения в одну карточку)', max_length=50, null=True),
        ),
    ]
