# Generated by Django 4.1 on 2024-09-27 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference_shared', '0032_lightningtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lightningtype',
            name='attribute_id',
            field=models.CharField(default='4458', max_length=50),
        ),
        migrations.AlterField(
            model_name='lightningtype',
            name='attribute_name',
            field=models.CharField(default='Покрытие экрана', max_length=50),
        ),
        migrations.AlterField(
            model_name='lightningtype',
            name='is_collection',
            field=models.BooleanField(default=False),
        ),
    ]
