# Generated by Django 4.1 on 2024-09-27 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference_shared', '0033_alter_lightningtype_attribute_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScreenCoating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_name', models.CharField(default='Покрытие экрана', max_length=50)),
                ('attribute_id', models.CharField(default='4458', max_length=50)),
                ('value', models.CharField(blank=True, max_length=100)),
                ('dictionary_value_id', models.CharField(default=0, max_length=20)),
                ('is_required', models.BooleanField(default=False)),
                ('category_dependent', models.BooleanField(default=False)),
                ('is_collection', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='lightningtype',
            name='attribute_id',
            field=models.CharField(default='4457', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lightningtype',
            name='attribute_name',
            field=models.CharField(default='Тип подсветки', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lightningtype',
            name='dictionary_value_id',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='lightningtype',
            name='is_collection',
            field=models.BooleanField(default=True),
        ),
    ]
