# Generated by Django 4.1 on 2024-10-05 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_monitor_reference', '0007_alter_builtinspeaker_dictionary_value_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorColour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_name', models.CharField(default='Цвет товара', max_length=50)),
                ('attribute_id', models.CharField(default='10096', max_length=50)),
                ('value', models.CharField(blank=True, max_length=100)),
                ('dictionary_value_id', models.CharField(default='1', max_length=20)),
                ('is_required', models.BooleanField(default=False)),
                ('category_dependent', models.BooleanField(default=True)),
                ('is_collection', models.BooleanField(default=True)),
            ],
        ),
    ]
