# Generated by Django 4.1 on 2024-10-05 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_monitor_reference', '0009_monitorbrand'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MonitorBrand',
            new_name='BrandMonitor',
        ),
        migrations.RenameModel(
            old_name='MonitorColour',
            new_name='ColourMonitor',
        ),
    ]
