# Generated by Django 4.1 on 2024-10-05 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_monitor_reference', '0010_rename_monitorbrand_brandmonitor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EuroAsianCodeMonitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_name', models.CharField(default='ТН ВЭД коды ЕАЭС', max_length=50)),
                ('attribute_id', models.CharField(default='22232', max_length=50)),
                ('value', models.CharField(blank=True, max_length=100)),
                ('dictionary_value_id', models.CharField(default=0, max_length=20)),
                ('is_required', models.BooleanField(default=False)),
                ('category_dependent', models.BooleanField(default=True)),
                ('is_collection', models.BooleanField(default=False)),
            ],
        ),
    ]
