# Generated by Django 4.1 on 2024-10-07 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_monitor_reference', '0011_euroasiancodemonitor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='euroasiancodemonitor',
            name='value',
            field=models.TextField(blank=True),
        ),
    ]
